export const COUNTRIES = [
  { name: 'Alemanha', code: 'DE' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Austrália', code: 'AU' },
  { name: 'Brasil', code: 'BR' },
  { name: 'Canadá', code: 'CA' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Espanha', code: 'ES' },
  { name: 'Estados Unidos', code: 'US' },
  { name: 'França', code: 'FR' },
  { name: 'Índia', code: 'IN' },
  { name: 'Itália', code: 'IT' },
  { name: 'Japão', code: 'JP' },
  { name: 'México', code: 'MX' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Reino Unido', code: 'GB' },
  { name: 'Rússia', code: 'RU' },
  { name: 'Suíça', code: 'CH' },
  { name: 'Uruguai', code: 'UY' },
];
